name: Docker Image CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU (only for arm64)
        if: matrix.platform == 'linux/arm64'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Branch Name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            swissartresearx/researchspace:${{ github.sha }}-${{ matrix.platform//\//- }}
            swissartresearx/researchspace:${{ github.sha }}

      - name: Build and Push Latest Tag (only for master)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: swissartresearx/researchspace:latest-${{ matrix.platform//\//- }}

      - name: Build and Push Develop Tag (only for develop branch)
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: swissartresearx/researchspace:${{ env.branch }}-${{ matrix.platform//\//- }}