name: Docker Image CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU (only for arm64)
        if: matrix.platform == 'linux/arm64'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Branch Name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Normalize Platform Name
        shell: bash
        run: echo "PLATFORM_TAG=$(echo '${{ matrix.platform }}' | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Build and Push Platform-Specific Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            swissartresearx/researchspace:${{ github.sha }}-${{ env.PLATFORM_TAG }}

  # Merge the architecture-specific images into one multi-arch image
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker buildx imagetools create -t swissartresearx/researchspace:${{ github.sha }} \
            swissartresearx/researchspace:${{ github.sha }}-linux-amd64 \
            swissartresearx/researchspace:${{ github.sha }}-linux-arm64

      - name: Create and Push "latest" Manifest (only for master)
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx imagetools create -t swissartresearx/researchspace:latest \
            swissartresearx/researchspace:${{ github.sha }}-linux-amd64 \
            swissartresearx/researchspace:${{ github.sha }}-linux-arm64

      - name: Create and Push "develop" Manifest (only for develop branch)
        if: github.ref == 'refs/heads/develop'
        run: |
          docker buildx imagetools create -t swissartresearx/researchspace:${{ env.branch }} \
            swissartresearx/researchspace:${{ github.sha }}-linux-amd64 \
            swissartresearx/researchspace:${{ github.sha }}-linux-arm64